jobs:
  include:
  - stage: Build

    language: go
    sudo: required
    services:
    - docker
    go : '1.10'
    after_success: |
      make docker-push

      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        bash <(curl -s https://codecov.io/bash)
      fi

  - stage: Publish

    sudo: required
    services:
    - docker
    script: |
      curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/go-api

      make docker-promote
      VERSION=latest make docker-push

  - stage: Deploy

    script: |
      sed \
        -e "s|\${ROLLBAR_TOKEN}|${ROLLBAR_TOKEN}|g" \
        docker-compose.yml > docker-compose-env.yml
    deploy:
      provider: script
      skip_cleanup: true
      script: 'curl -H "Authorization: GitHub ${GITHUB_OAUTH_TOKEN}" -X POST "https://dashboard-api.vibioh.fr/deploy/`make name`/?rollbar_token=${ROLLBAR_TOKEN}&user=`make author`&revision=`make version`&environment=prod" --data-binary @docker-compose-env.yml'

stages:
  - Build
  - name: Publish
    if: branch = master
  - name: Deploy
    if: branch = master

notifications:
  email: false
