jobs:
  include:
  - stage: Build

    language: go
    sudo: required
    services:
    - docker
    go : '1.10'
    after_success: |
      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        bash <(curl -s https://codecov.io/bash)
        curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/go-api

        make docker-push
      fi

  - stage: Deploy

    script: |
      sed \
        -e "s|\${ROLLBAR_TOKEN}|${ROLLBAR_TOKEN}|g" \
        docker-compose.yml > docker-compose-env.yml
    deploy:
      provider: script
      skip_cleanup: true
      script: 'curl -H "Authorization: GitHub ${GITHUB_OAUTH_TOKEN}" -X POST "https://dashboard-api.vibioh.fr/deploy/api/?rollbar_token=${ROLLBAR_TOKEN}&user=`make author`&revision=`make version`&environment=prod" --data-binary @docker-compose-env.yml'

stages:
  - Build
  - name: Deploy
    if: branch = master

notifications:
  email: false
