language: go
sudo: required
services:
- docker
go: 1.8
install: make
script: |
  DOCKER_IMAGE_NAME=${DOCKER_USER}/api
  if [ "${TRAVIS_BRANCH}" != "master" ]; then
    DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}
  fi
  
  docker build -t ${DOCKER_IMAGE_NAME} .
after_success: |
  docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && docker push ${DOCKER_IMAGE_NAME}
notifications:
  email: false
deploy:
  provider: script
  skip_cleanup: true
  script: curl -u ${DEPLOY_USER}:${DEPLOY_PASS} -X POST https://dashboard-api.vibioh.fr/containers/api/ --data-binary @docker-compose.yml
  on:
    condition: "${TRAVIS_BRANCH}" == "master"
