language: go
sudo: required
services:
- docker
go:
- 1.7
install: make
script:
- docker build -t ${DOCKER_USER}/api .
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- docker push ${DOCKER_USER}/api
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_afb3f4a0fd37_key -iv $encrypted_afb3f4a0fd37_iv -in deploy_rsa.enc -out deploy_rsa -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "bash -s" -- < ./deploy.sh api https://github.com/ViBiOh/go-hello.git vibioh.fr api
  on:
    branch: master
