version: '2'

services:
  api:
    image: vibioh/api
    command:
    - -datadogService
    - api
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: api.vibioh.fr'
      traefik.protocol: 'https'
      traefik.port: '1080'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    external_links:
    - datadog_agent_1:dd-agent
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 25165824
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
