---

version: "2"

services:
  api:
    image: vibioh/api
    labels:
      traefik.http.routers.api-http.rule: Host(`api.vibioh.fr`)
      traefik.http.routers.api-http.entrypoints: http
      traefik.http.routers.api-http.middlewares: redirect@file
      traefik.http.routers.api-https.rule: Host(`api.vibioh.fr`)
      traefik.http.routers.api-https.entrypoints: https
      traefik.http.routers.api-https.middlewares: compress@file, web-limit@file
      traefik.http.routers.api-https.tls: true
      traefik.http.routers.api-https.tls.certresolver: default
      traefik.http.services.api-service.loadbalancer.server.port: "1080"
    environment:
      API_CORS_METHODS: GET,OPTIONS,POST,PUT,DELETE
      API_CSP: "default-src 'self'; base-uri 'self'; script-src 'self' 'unsafe-inline' unpkg.com/swagger-ui-dist@3/; style-src 'self' 'unsafe-inline' unpkg.com/swagger-ui-dist@3/; img-src 'self' data:; connect-src 'self' api.vibioh.fr"
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 25165824
    security_opt:
      - no-new-privileges
