version: '2'

services:
  api:
    image: vibioh/api
    command:
    - -prometheusMetricsRemoteHost
    - ^api:1080$$
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: api.vibioh.fr'
      traefik.protocol: 'https'
      traefik.port: '1080'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
